version = 0.1

[default]
[default.build]
[default.build.parameters]
cached = true
parallel = true

[default.validate]
[default.validate.parameters]
lint = true

[default.deploy]
[default.deploy.parameters]
stack_name = "bedrock-openai-proxy-dev"
s3_prefix = "bedrock-openai-proxy"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=dev"
image_repositories = []

[dev]
[dev.build]
[dev.build.parameters]
cached = true
parallel = true

[dev.deploy]
[dev.deploy.parameters]
stack_name = "bedrock-openai-proxy-dev"
s3_prefix = "bedrock-openai-proxy-dev"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=dev"

[staging]
[staging.deploy]
[staging.deploy.parameters]
stack_name = "bedrock-openai-proxy-staging"
s3_prefix = "bedrock-openai-proxy-staging"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=staging"

[prod]
[prod.deploy]
[prod.deploy.parameters]
stack_name = "bedrock-openai-proxy-prod"
s3_prefix = "bedrock-openai-proxy-prod"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=prod"